/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_tictactoe;

public class Main {
    public static void main(String[] args) {
        
        TicTacToe game = new TicTacToe();
    }
}
